# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313512aba01a7f0e1102f442859517c3995327332214f064271da6cb66a0addf140aaa674237b65b8a82150904938a3de5f089334a62930c214d679c9d7e95a0

test:
  secret_key_base: 44901fc8e0611eb47923747858cdbc4899ddca502a633f8645fcdb8817489d19dff1ce87979e0d7e4ac715d6e3b5219660a3d758404b0ff892ff948ded1a7339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
